version: '3.7'
services:
  monolith-mongo:
    image: mongo:7
    ports:
      - 27017:27017
  monolith:
    build:
      context: .
      dockerfile: Dockerfile.monolith
    ports:
      - 8080:8080
    environment:
      SERVICE_PORT: 8080
      DB_HOSTNAME: monolith-mongo
      WAIT_HOSTS: monolith-mongo:27017