version: '3.7'
services:
  three-mongo:
    image: mongo:7
    ports:
      - 27017:27017

  three-user:
    build:
      context: .
      dockerfile: Dockerfile.microservice
      args:
        TYPE: three_microservices
        SERVICE: user
    ports:
      - 8082:8082
    environment:
      SERVICE_PORT: 8082
      DB_HOSTNAME: three-mongo
      WAIT_HOSTS: three-mongo:27017

  three-session:
    build:
      context: .
      dockerfile: Dockerfile.microservice
      args:
        TYPE: three_microservices
        SERVICE: session
    ports:
      - 8081:8081
    environment:
      SERVICE_PORT: 8081
      USER_BASE_URL: http://three-user:8082
      DB_HOSTNAME: three-mongo
      WAIT_HOSTS: three-mongo:27017, three-user:8082

  three-auth:
    build:
      context: .
      dockerfile: Dockerfile.microservice
      args:
        TYPE: three_microservices
        SERVICE: auth
    ports:
      - 8080:8080
    environment:
      SERVICE_PORT: 8080
      SESSION_BASE_URL: http://three-session:8081
      USER_BASE_URL: http://three-user:8082
      DB_HOSTNAME: three-mongo
      WAIT_HOSTS: three-mongo:27017, three-session:8081, three-user:8082